/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as MainNextActionsRouteImport } from './routes/_main/next-actions'
import { Route as MainInboxRouteImport } from './routes/_main/inbox'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRoute,
} as any)
const MainNextActionsRoute = MainNextActionsRouteImport.update({
  id: '/next-actions',
  path: '/next-actions',
  getParentRoute: () => MainRoute,
} as any)
const MainInboxRoute = MainInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/inbox': typeof MainInboxRoute
  '/next-actions': typeof MainNextActionsRoute
  '/projects': typeof MainProjectsRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/inbox': typeof MainInboxRoute
  '/next-actions': typeof MainNextActionsRoute
  '/projects': typeof MainProjectsRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_main/inbox': typeof MainInboxRoute
  '/_main/next-actions': typeof MainNextActionsRoute
  '/_main/projects': typeof MainProjectsRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/inbox' | '/next-actions' | '/projects' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/inbox' | '/next-actions' | '/projects' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_main/inbox'
    | '/_main/next-actions'
    | '/_main/projects'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/next-actions': {
      id: '/_main/next-actions'
      path: '/next-actions'
      fullPath: '/next-actions'
      preLoaderRoute: typeof MainNextActionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inbox': {
      id: '/_main/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof MainInboxRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainInboxRoute: typeof MainInboxRoute
  MainNextActionsRoute: typeof MainNextActionsRoute
  MainProjectsRoute: typeof MainProjectsRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainInboxRoute: MainInboxRoute,
  MainNextActionsRoute: MainNextActionsRoute,
  MainProjectsRoute: MainProjectsRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
