/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemetestRouteImport } from './routes/themetest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as UserCreateRouteImport } from './routes/user.create'
import { Route as MainTest2RouteImport } from './routes/_main/test2'
import { Route as MainTestRouteImport } from './routes/_main/test'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as MainInboxRouteImport } from './routes/_main/inbox'

const ThemetestRoute = ThemetestRouteImport.update({
  id: '/themetest',
  path: '/themetest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const UserCreateRoute = UserCreateRouteImport.update({
  id: '/user/create',
  path: '/user/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTest2Route = MainTest2RouteImport.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => MainRoute,
} as any)
const MainTestRoute = MainTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRoute,
} as any)
const MainInboxRoute = MainInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/themetest': typeof ThemetestRoute
  '/inbox': typeof MainInboxRoute
  '/projects': typeof MainProjectsRoute
  '/test': typeof MainTestRoute
  '/test2': typeof MainTest2Route
  '/user/create': typeof UserCreateRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/themetest': typeof ThemetestRoute
  '/inbox': typeof MainInboxRoute
  '/projects': typeof MainProjectsRoute
  '/test': typeof MainTestRoute
  '/test2': typeof MainTest2Route
  '/user/create': typeof UserCreateRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/themetest': typeof ThemetestRoute
  '/_main/inbox': typeof MainInboxRoute
  '/_main/projects': typeof MainProjectsRoute
  '/_main/test': typeof MainTestRoute
  '/_main/test2': typeof MainTest2Route
  '/user/create': typeof UserCreateRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/themetest'
    | '/inbox'
    | '/projects'
    | '/test'
    | '/test2'
    | '/user/create'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/themetest'
    | '/inbox'
    | '/projects'
    | '/test'
    | '/test2'
    | '/user/create'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/themetest'
    | '/_main/inbox'
    | '/_main/projects'
    | '/_main/test'
    | '/_main/test2'
    | '/user/create'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  ThemetestRoute: typeof ThemetestRoute
  UserCreateRoute: typeof UserCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themetest': {
      id: '/themetest'
      path: '/themetest'
      fullPath: '/themetest'
      preLoaderRoute: typeof ThemetestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/user/create': {
      id: '/user/create'
      path: '/user/create'
      fullPath: '/user/create'
      preLoaderRoute: typeof UserCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/test2': {
      id: '/_main/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof MainTest2RouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/test': {
      id: '/_main/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof MainTestRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inbox': {
      id: '/_main/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof MainInboxRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainInboxRoute: typeof MainInboxRoute
  MainProjectsRoute: typeof MainProjectsRoute
  MainTestRoute: typeof MainTestRoute
  MainTest2Route: typeof MainTest2Route
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainInboxRoute: MainInboxRoute,
  MainProjectsRoute: MainProjectsRoute,
  MainTestRoute: MainTestRoute,
  MainTest2Route: MainTest2Route,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  ThemetestRoute: ThemetestRoute,
  UserCreateRoute: UserCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
