"""message

Revision ID: 073bf9a24d59
Revises: 6a7e23771287
Create Date: 2025-05-10 16:55:50.548417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073bf9a24d59'
down_revision: Union[str, None] = '6a7e23771287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index('ix_actions_inbox_item_id', table_name='actions')
    op.drop_constraint('actions_inbox_item_id_fkey', 'actions', type_='foreignkey')
    op.drop_column('actions', 'inbox_item_id')
    op.add_column('inbox_items', sa.Column('action_id', sa.UUID(), nullable=True))
    op.add_column('inbox_items', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inbox_items_action_id'), 'inbox_items', ['action_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_project_id'), 'inbox_items', ['project_id'], unique=False)
    op.create_foreign_key(None, 'inbox_items', 'actions', ['action_id'], ['id'])
    op.create_foreign_key(None, 'inbox_items', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox_items', type_='foreignkey')
    op.drop_constraint(None, 'inbox_items', type_='foreignkey')
    op.drop_index(op.f('ix_inbox_items_project_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_action_id'), table_name='inbox_items')
    op.drop_column('inbox_items', 'project_id')
    op.drop_column('inbox_items', 'action_id')
    op.add_column('actions', sa.Column('inbox_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('actions_inbox_item_id_fkey', 'actions', 'inbox_items', ['inbox_item_id'], ['id'])
    op.create_index('ix_actions_inbox_item_id', 'actions', ['inbox_item_id'], unique=False)
    # ### end Alembic commands ###
