"""init db

Revision ID: 09b6c1c852b6
Revises: 
Create Date: 2025-04-27 21:40:24.628479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models.views.inbox import InboxItemWithTranscription
from fastapi_users_db_sqlalchemy import generics


# revision identifiers, used by Alembic.
revision: str = '09b6c1c852b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_transcription', 'audios', ['transcription'], unique=False)
    op.create_index(op.f('ix_audios_deleted_at'), 'audios', ['deleted_at'], unique=False)
    op.create_table('images',
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_ai_description', 'images', ['ai_description'], unique=False)
    op.create_index(op.f('ix_images_deleted_at'), 'images', ['deleted_at'], unique=False)
    op.create_table('projects',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', name='project_status_enum'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accesstoken',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    op.create_table('inbox_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=True),
    sa.Column('audio_id', sa.UUID(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbox_user_processed', 'inbox_items', ['user_id', 'processed'], unique=False)
    op.create_index(op.f('ix_inbox_items_audio_id'), 'inbox_items', ['audio_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_deleted_at'), 'inbox_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_inbox_items_image_id'), 'inbox_items', ['image_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_user_id'), 'inbox_items', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_oauth_name'), 'oauth_accounts', ['oauth_name'], unique=False)
    op.create_table('actions',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DEFERRED', name='action_status_enum'), nullable=True),
    sa.Column('inbox_item_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_due_date_status', 'actions', ['due_date', 'status'], unique=False)
    op.create_index(op.f('ix_actions_deleted_at'), 'actions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_actions_inbox_item_id'), 'actions', ['inbox_item_id'], unique=False)
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.create_table('capture_project_links',
    sa.Column('capture_item_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capture_item_id'], ['inbox_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('capture_item_id', 'project_id')
    )
    op.create_table('references',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('inbox_item_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_deleted_at'), 'references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_references_inbox_item_id'), 'references', ['inbox_item_id'], unique=False)
    op.create_table('someday_maybe',
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inbox_item_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_someday_maybe_deleted_at'), 'someday_maybe', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_someday_maybe_inbox_item_id'), 'someday_maybe', ['inbox_item_id'], unique=True)
    op.create_table('reference_tag_links',
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('reference_id', 'tag_id')
    )
    
    InboxItemWithTranscription.create_view(op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    InboxItemWithTranscription.drop_view(op)
    op.drop_table('reference_tag_links')
    op.drop_index(op.f('ix_someday_maybe_inbox_item_id'), table_name='someday_maybe')
    op.drop_index(op.f('ix_someday_maybe_deleted_at'), table_name='someday_maybe')
    op.drop_table('someday_maybe')
    op.drop_index(op.f('ix_references_inbox_item_id'), table_name='references')
    op.drop_index(op.f('ix_references_deleted_at'), table_name='references')
    op.drop_table('references')
    op.drop_table('capture_project_links')
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_inbox_item_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_deleted_at'), table_name='actions')
    op.drop_index('idx_action_due_date_status', table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_oauth_accounts_oauth_name'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_inbox_items_user_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_image_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_deleted_at'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_audio_id'), table_name='inbox_items')
    op.drop_index('idx_inbox_user_processed', table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_images_deleted_at'), table_name='images')
    op.drop_index('idx_image_ai_description', table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_audios_deleted_at'), table_name='audios')
    op.drop_index('idx_audio_transcription', table_name='audios')
    op.drop_table('audios')
    # ### end Alembic commands ###
