"""message

Revision ID: 3e1e8dfcef1e
Revises: 073bf9a24d59
Create Date: 2025-05-10 17:10:11.793057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1e8dfcef1e'
down_revision: Union[str, None] = '073bf9a24d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_items', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox_items', 'is_new')
    # ### end Alembic commands ###
