"""migration message

Revision ID: 6a7e23771287
Revises: 09b6c1c852b6
Create Date: 2025-04-29 22:15:14.484888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7e23771287'
down_revision: Union[str, None] = '09b6c1c852b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'actions', 'users', ['user_id'], ['id'])
    op.add_column('audios', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_audios_user_id'), 'audios', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audios', 'users', ['user_id'], ['id'])
    op.add_column('images', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'inbox_items', 'users', ['user_id'], ['id'])
    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.add_column('references', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_references_user_id'), 'references', ['user_id'], unique=False)
    op.create_foreign_key(None, 'references', 'users', ['user_id'], ['id'])
    op.add_column('someday_maybe', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_someday_maybe_user_id'), 'someday_maybe', ['user_id'], unique=False)
    op.create_foreign_key(None, 'someday_maybe', 'users', ['user_id'], ['id'])
    op.add_column('tags', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_column('tags', 'user_id')
    op.drop_constraint(None, 'someday_maybe', type_='foreignkey')
    op.drop_index(op.f('ix_someday_maybe_user_id'), table_name='someday_maybe')
    op.drop_column('someday_maybe', 'user_id')
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.drop_index(op.f('ix_references_user_id'), table_name='references')
    op.drop_column('references', 'user_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'inbox_items', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_column('images', 'user_id')
    op.drop_constraint(None, 'audios', type_='foreignkey')
    op.drop_index(op.f('ix_audios_user_id'), table_name='audios')
    op.drop_column('audios', 'user_id')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.drop_column('actions', 'user_id')
    # ### end Alembic commands ###
