"""message

Revision ID: 7226c864c677
Revises: 0ca395c5a43b
Create Date: 2025-06-27 16:36:31.712605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7226c864c677'
down_revision: Union[str, None] = '0ca395c5a43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_user_id_fkey', 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
