"""init commit

Revision ID: 86cf50278676
Revises: c60a85d339dd
Create Date: 2025-04-12 14:06:41.570550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cf50278676'
down_revision: Union[str, None] = 'c60a85d339dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_transcription', 'audios', ['transcription'], unique=False)
    op.create_index(op.f('ix_audios_deleted_at'), 'audios', ['deleted_at'], unique=False)
    op.add_column('inbox_items', sa.Column('audio_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inbox_items_audio_id'), 'inbox_items', ['audio_id'], unique=False)
    op.create_foreign_key(None, 'inbox_items', 'audios', ['audio_id'], ['id'])
    op.drop_column('inbox_items', 'audio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_items', sa.Column('audio_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbox_items', type_='foreignkey')
    op.drop_index(op.f('ix_inbox_items_audio_id'), table_name='inbox_items')
    op.drop_column('inbox_items', 'audio_id')
    op.drop_index(op.f('ix_audios_deleted_at'), table_name='audios')
    op.drop_index('idx_audio_transcription', table_name='audios')
    op.drop_table('audios')
    # ### end Alembic commands ###
