"""message

Revision ID: b7863d31752e
Revises: 7590a802d08f
Create Date: 2025-05-20 22:18:20.412750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.features.extended_inbox.model import ExtendedInbox


# revision identifiers, used by Alembic.
revision: str = 'b7863d31752e'
down_revision: Union[str, None] = '7590a802d08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ExtendedInbox.create_view(op)
    op.add_column('tags', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tags', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tags', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ExtendedInbox.drop_view(op)
    op.add_column('tags', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tags', 'description')
    op.drop_column('tags', 'color')
    # ### end Alembic commands ###
